# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: News
    url: /#news
    weight: 20
  - name: Research
    url: /#research
    weight: 30
  - name: People
    url: /#people
    weight: 40
  - name: Publications
    url: /#publications
    weight: 50
  - name: Positions
    url: /#positions
    weight: 60
  - name: Funding Opportunities
    weight: 70
    hasChildren: true
  - parent: Funding Opportunities
    name: Postdocs
    url: blog/
