# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Features
    url: /#features
    weight: 30
  - name: Solutions
    url: /#solutions
    weight: 50
  - name: Opportunities
    url: /#opportunities
    weight: 60
  - name: Resources
    weight: 70
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
