# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo landing page theme powered by Hugo Blox website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: '<span style="font-family:Poppins, sans-serif; font-weight:600; font-size:1.2rem; color:#111;">Cao <span style="color:#DA0037">Research Group</span></span>'
      # Logo filename in `assets/media/` folder
      filename: "log1.png"
    button:
      enable: true
      text: "Get Started"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} My Company'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
